#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

main() {
  local version="${VERSION:-1.19.0}"

  export VERSION="$version"
  envsubst < "$SCRIPT_DIR"/dockerfile \
    | docker build "$@" -t adoyle/mycli:"$version" -
}

main "$@"
