#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

main() {
  local version="${VERSION:-1.19.0}"
  docker run --net=host --rm -it adoyle/mycli:"$version" "$@"
}

main "$@"
